;; Some logos taken from NeoFetch, some modified
;;  https://github.com/dylanaraps/neofetch


#lang racket/base


(provide
 system-logos
 )


(define system-logos
  (hash

   "Other"
   '(
    "  ___   ______ __  __  ____ ____ "
    " // \\  | || | ||  || ||    || \\"
    "((   ))   ||   ||==|| ||==  ||_//"
    " \\_//    ||   ||  || ||___ || \\"
    )

   "Unix"
   '(
     "__ __ __  __ __ _   _"
     "|| || ||\\ || || \\\\ //"
     "|| || ||\\\\|| ||  )X( "
     "\\\\_// || \\|| || // \\\\"
     )

   "Linux"
   '(
     "        #####"
     "       #######"
     "       ##O#O##"
     "       #######"
     "     ###########"
     "    #############"
     "   ###############"
     "   ################"
     "  #################"
     "#####################"
     "#####################"
     "  #################"
     )

   "Macos"
   '(
     "                    'c."
     "                 ,xNMM."
     "               .OMMMMo"
     "               OMMM0,"
     "     .;loddo:' loolloddol;."
     "   cKMMMMMMMMMMNWMMMMMMMMMM0:"
     " .KMMMMMMMMMMMMMMMMMMMMMMMWd."
     " XMMMMMMMMMMMMMMMMMMMMMMMX."
     ";MMMMMMMMMMMMMMMMMMMMMMMM:"
     ":MMMMMMMMMMMMMMMMMMMMMMMM:"
     ".MMMMMMMMMMMMMMMMMMMMMMMMX."
     " kMMMMMMMMMMMMMMMMMMMMMMMMWd."
     " .XMMMMMMMMMMMMMMMMMMMMMMMMMMk"
     "  .XMMMMMMMMMMMMMMMMMMMMMMMMK."
     "    kMMMMMMMMMMMMMMMMMMMMMMd"
     "     ;KMMMMMMMWXXWMMMMMMMk."
     "       .cooc,.    .,coo:."
     )

   "Windows"
   '(
     "                                ..,"
     "                    ....,,:;+ccllll"
     "      ...,,+:;  cllllllllllllllllll"
     ",cclllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     ""
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "llllllllllllll  lllllllllllllllllll"
     "``''llllllllll  lllllllllllllllllll"
     "       ``'':::  :ccllllllllllllllll"
     "                       ````''*::cll"
     "                                 ``"
     )

   ;; BSD   distributions

   "Freebsd"
   '(
     "```                        `"
     "  ` `.....---.......--.```   -/"
     "  +o   .--`         /y:`      +."
     "   yo`:.            :o      `+-"
     "    y/               -/`   -o/"
     "   .-                  ::/sy+:."
     "   /                     `--  /"
     "  `:                          :`"
     "  `:                          :`"
     "   /                          /"
     "   .-                        -."
     "    --                      -."
     "     `:`                  `:`"
     "       .--             `--."
     "          .---.....----."
     )

   "Openbsd"
   '(
     "                                     _"
     "                                    (_)"
     "              |    ."
     "          .   |L  /|   .          _"
     "      _ . |\\ _| \\--+._/| .       (_)"
     "     / ||\\| Y J  )   / |/| ./"
     "    J  |)'( |        ` F`.'/        _"
     "  -<|  F         __     .-<        (_)"
     "    | /       .-'. `.  /-. L___"
     "    J \\      <    \\  | | O\\|.-'  _"
     "  _J \\  .-    \\/ O | | \\  |F    (_)"
     " '-F  -<_.     \\   .-'  `-' L__"
     "__J  _   _.     >-'  )._.   |-'"
     " `-|.'   /_.          \\_|   F"
     "  /.-   .                _.<"
     " /'    /.'             .'  `\\"
     "  /L  /'   |/      _.-'-\\"
     " /'J       ___.---'\\|"
     "   |\\  .--' V  | `. `"
     "   |/`. `-.     `._)"
     "      / .-.\\"
     "      \\ (  `\\"
     "       `.\\"
     )

   "Netbsd"
   '(
     "                     `-/oshdmNMNdhyo+:-`"
     "y/s+:-``    `.-:+oydNMMMMNhs/-``"
     "-m+NMMMMMMMMMMMMMMMMMMMNdhmNMMMmdhs+/-`"
     " -m+NMMMMMMMMMMMMMMMMMMMMmy+:`"
     "  -N/dMMMMMMMMMMMMMMMds:`"
     "   -N/hMMMMMMMMMmho:`"
     "    -N/-:/++/:.`"
     "     :M+"
     "      :Mo"
     "       :Ms"
     "        :Ms"
     "         :Ms"
     "          :Ms"
     "           :Ms"
     "            :Ms"
     "             :Ms"
     "              :Ms"
     )

   ;; Linux distributions

   "Alpine"
   '(
     "       .hddddddddddddddddddddddh."
     "      :dddddddddddddddddddddddddd:"
     "     /dddddddddddddddddddddddddddd/"
     "    +dddddddddddddddddddddddddddddd+"
     "  `sdddddddddddddddddddddddddddddddds`"
     " `ydddddddddddd++hdddddddddddddddddddy`"
     ".hddddddddddd+`  `+ddddh:-sdddddddddddh."
     "hdddddddddd+`      `+y:    .sddddddddddh"
     "ddddddddh+`   `//`   `.`     -sddddddddd"
     "ddddddh+`   `/hddh/`   `:s-    -sddddddd"
     "ddddh+`   `/+/dddddh/`   `+s-    -sddddd"
     "ddd+`   `/o` :dddddddh/`   `oy-    .yddd"
     "hdddyo+ohddyosdddddddddho+oydddy++ohdddh"
     ".hddddddddddddddddddddddddddddddddddddh."
     " `yddddddddddddddddddddddddddddddddddy`"
     "  `sdddddddddddddddddddddddddddddddds`"
     "    +dddddddddddddddddddddddddddddd+"
     "     /dddddddddddddddddddddddddddd/"
     "      :dddddddddddddddddddddddddd:"
     "       .hddddddddddddddddddddddh."
     )

   "Arch"
   '(
     "                   -`"
     "                  .o+`"
     "                 `ooo/"
     "                `+oooo:"
     "               `+oooooo:"
     "               -+oooooo+:"
     "             `/:-:++oooo+:"
     "            `/++++/+++++++:"
     "           `/++++++++++++++:"
     "          `/+++ooooooooooooo/`"
     "         ./ooosssso++osssssso+`"
     "        .oossssso-````/ossssss+`"
     "       -osssssso.      :ssssssso."
     "      :osssssss/        osssso+++."
     "     /ossssssss/        +ssssooo/-"
     "   `/ossssso+/:-        -:/+osssso+-"
     "  `+sso+:-`                 `.-/+oso:"
     " `++:.                           `-/+/"
     " .`                                 `/"
     )

   "Ataraxia"
   '(
     "                    'l:"
     "        loooooo"
     "          loooo coooool"
     " looooooooooooooooooool"
     "  looooooooooooooooo"
     "         lool   cooo"
     "        coooooooloooooooo"
     "     clooooo  ;lood  cloooo"
     "  :loooocooo cloo      loooo"
     " loooo  :ooooool       loooo"
     "looo    cooooo        cooooo"
     "looooooooooooo      ;loooooo looooooc"
     "looooooooo loo   cloooooool    looooc"
     " cooo       cooooooooooo       looolooooool"
     "            cooo:     coooooooooooooooooool"
     "                       loooooooooooolc:   loooc;"
     "                             cooo:    loooooooooooc"
     "                            ;oool         looooooo:"
     "                           coool          olc,"
     "                          looooc   ,,"
     "                        coooooc    loc"
     "                       :oooool,    coool:, looool:,"
     "                       looool:      ooooooooooooooo:"
     "                       cooolc        .ooooooooooool"
     )

   "Debian"
   '(
     "       _,met$$$$$gg."
     "    ,g$$$$$$$$$$$$$$$P."
     "  ,g$$P''     ''''''Y$$.''."
     " ,$$P'              `$$$."
     "',$$P       ,ggs.     `$$b:"
     "`d$$'     ,$P'''   .    $$$"
     " $$P      d$'     ,    $$P"
     " $$:      $$.   -    ,d$$'"
     " $$;      Y$b._   _,d$P'"
     " Y$$.    `.`''Y$$$$P'''"
     " `$$b      ''-.__"
     "  `Y$$"
     "   `Y$$."
     "     `$$b."
     "       `Y$$b."
     "          `''Y$b._"
     "              `''''''"
     )

   "Fedora"
   '(
     "          /:-------------:\\"
     "       :-------------------::"
     "     :-----------/shhOHbmp---:\\"
     "   /-----------omMMMNNNMMD  ---:"
     "  :-----------sMMMMNMNMP.    ---:"
     " :-----------:MMMdP-------    ---\\"
     ",------------:MMMd--------    ---:"
     ":------------:MMMd-------    .---:"
     ":----    oNMMMMMMMMMNho     .----:"
     ":--     .+shhhMMMmhhy++   .------/"
     ":-    -------:MMMd--------------:"
     ":-   --------/MMMd-------------;"
     ":-    ------/hMMMy------------:"
     ":-- :dMNdhhdNMMNo------------;"
     ":---:sdNMMMMNds:------------:"
     ":------:://:-------------::"
     ":---------------------://"
     )

   "Gentoo"
   '(
     "         -/oyddmdhs+:."
     "     -odNMMMMMMMMNNmhy+-`"
     "   -yNMMMMMMMMMMMNNNmmdhy+-"
     " `omMMMMMMMMMMMMNmdmmmmddhhy/`"
     " omMMMMMMMMMMMNhhyyyohmdddhhhdo`"
     ".ydMMMMMMMMMMdhs++so/smdddhhhhdm+`"
     " oyhdmNMMMMMMMNdyooydmddddhhhhyhNd."
     "  :oyhhdNNMMMMMMMNNNmmdddhhhhhyymMh"
     "    .:+sydNMMMMMNNNmmmdddhhhhhhmMmy"
     "       /mMMMMMMNNNmmmdddhhhhhmMNhs:"
     "    `oNMMMMMMMNNNmmmddddhhdmMNhs+`"
     "  `sNMMMMMMMMNNNmmmdddddmNMmhs/."
     " /NMMMMMMMMNNNNmmmdddmNMNdso:`"
     "+MMMMMMMNNNNNmmmmdmNMNdso/-"
     "yMMNNNNNNNmmmmmNNMmhs+/-`"
     "/hMMNNNNNNNNMNdhs++/-`"
     "`/ohdmmddhys+++/:.`"
     "  `-//////:--."
     )

   "Guixsd"
   '(
     " ..                             `."
     " `--..```..`           `..```..--`"
     "   .-:///-:::.       `-:::///:-."
     "      ````.:::`     `:::.````"
     "           -//:`    -::-"
     "            ://:   -::-"
     "            `///- .:::`"
     "             -+++-:::."
     "              :+/:::-"
     "              `-....`"
     )

   "Nixos"
   '(
     "          ::::.    ':::::     ::::'"
     "          ':::::    ':::::.  ::::'"
     "            :::::     '::::.:::::"
     "      .......:::::..... ::::::::"
     "     ::::::::::::::::::. ::::::    ::::."
     "    ::::::::::::::::::::: :::::.  .::::'"
     "           .....           ::::' :::::'"
     "          :::::            '::' :::::'"
     " ........:::::               ' :::::::::::."
     ":::::::::::::                 :::::::::::::"
     " ::::::::::: ..              :::::"
     "     .::::: .:::            :::::"
     "    .:::::  :::::          '''''    ....."
     "    :::::   ':::::.  ......:::::::::::::'"
     "     :::     ::::::. ':::::::::::::::::'"
     "            .:::::::: '::::::::::"
     "           .::::''::::.     '::::."
     "          .::::'   ::::.     '::::."
     "         .::::      ::::      '::::."
     )

   "Redhat"
   '(
     "           .MMM..:MMMMMMM"
     "          MMMMMMMMMMMMMMMMMM"
     "          MMMMMMMMMMMMMMMMMMMM."
     "         MMMMMMMMMMMMMMMMMMMMMM"
     "        ,MMMMMMMMMMMMMMMMMMMMMM:"
     "        MMMMMMMMMMMMMMMMMMMMMMMM"
     "  .MMMM'  MMMMMMMMMMMMMMMMMMMMMM"
     " MMMMMM    `MMMMMMMMMMMMMMMMMMMM."
     "MMMMMMMM      MMMMMMMMMMMMMMMMMM ."
     "MMMMMMMMM.       `MMMMMMMMMMMMM' MM."
     "MMMMMMMMMMM.                     MMMM"
     "`MMMMMMMMMMMMM.                 ,MMMMM."
     " `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM."
     "    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
     "      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:"
     "         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
     "            `MMMMMMMMMMMMMMMMMMMMMMMM:"
     "                ``MMMMMMMMMMMMMMMMM'"
     )

   "Slackware"
   '(
     "                  :::::::"
     "            :::::::::::::::::::"
     "         :::::::::::::::::::::::::"
     "       ::::::::cllcccccllllllll::::::"
     "    :::::::::lc               dc:::::::"
     "   ::::::::cl   clllccllll    oc:::::::::"
     "  :::::::::o   lc::::::::co   oc::::::::::"
     " ::::::::::o    cccclc:::::clcc::::::::::::"
     " :::::::::::lc        cclccclc:::::::::::::"
     "::::::::::::::lcclcc          lc::::::::::::"
     "::::::::::cclcc:::::lccclc     oc:::::::::::"
     "::::::::::o    l::::::::::l    lc:::::::::::"
     " :::::cll:o     clcllcccll     o:::::::::::"
     " :::::occ:o                  clc:::::::::::"
     "  ::::ocl:ccslclccclclccclclc:::::::::::::"
     "   :::oclcccccccccccccllllllllllllll:::::"
     "    ::lcc1lcccccccccccccccccccccccco::::"
     "      ::::::::::::::::::::::::::::::::"
     "        ::::::::::::::::::::::::::::"
     "           ::::::::::::::::::::::"
     "                ::::::::::::"
     )

   "Suse"
   '(
     "           .;ldkO0000Okdl;."
     "       .;d00xl:^''''''^:ok00d;."
     "     .d00l'                'o00d."
     "   .d0Kd'  Okxol:;,.          :O0d."
     "  .OKKKK0kOKKKKKKKKKKOxo:,      lKO."
     " ,0KKKKKKKKKKKKKKKK0P^,,,^dx:    ;00,"
     ".OKKKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO."
     ":KKKKKKKKKKKKKKKKK: kKx..dd lKd   'OK:"
     "dKKKKKKKKKKKOx0KKKd ^0KKKO' kKKc   dKd"
     "dKKKKKKKKKKKK;.;oOKx,..^..;kKKK0.  dKd"
     ":KKKKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:"
     " kKKKKKKKKKKKKKKK0x;,,......,;od  lKk"
     " '0KKKKKKKKKKKKKKKKKKKKK00KKOo^  c00'"
     "  'kKKKOxddxkOO00000Okxoc;''   .dKk'"
     "    l0Ko.                    .c00l'"
     "     'l0Kk:.              .;xK0l'"
     "        'lkK0xl:;,,,,;:ldO0kl'"
     "            '^:ldxkkkkxdl:^'"
     )

   "Void"
   '(
     "                __.;=====;.__"
     "            _.=+==++=++=+=+===;."
     "             -=+++=+===+=+=+++++=_"
     "        .     -=:``     `--==+=++==."
     "       _vi,    `            --+=++++:"
     "      .uvnvi.       _._       -==+==+."
     "     .vvnvnI`    .;==|==;.     :|=||=|."
     "+QmQQmpvvnv; _yYsyQQWUUQQQm #QmQ#:QQQWUV$QQm."
     " -QQWQWpvvowZ?.wQQQE==<QWWQ/QWQW.QQWW(: jQWQE"
     "  -$QQQQmmU'  jQQQ@+=<QWQQ)mQQQ.mQQQC+;jWQQ@'"
     "   -$WQ8YnI:   QWQQwgQQWV`mWQQ.jQWQQgyyWW@!"
     "     -1vvnvv.     `~+++`        ++|+++"
     "      +vnvnnv,                 `-|==="
     "       +vnvnvns.           .      :=-"
     "        -Invnvvnsi..___..=sv=.     `"
     "          +Invnvnvnnnnnnnnvvnn;."
     "            ~|Invnvnvvnvvvnnv}+`"
     "               -~|{*l}*|~"
     )

   )
  )
